version: "3.8"
services:
  database:
      environment:
        - NEO4J_AUTH=none
        - SECURE_FILE_PERMISSIONS=yes
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      ports:
        - 7474:7474
        - 7687:7687
      # image: neo4j:4.2
      image: neo4j:4.2.0-enterprise
      volumes:
        - "./neo4j-data:/data"